name: Validation

on:
  workflow_dispatch:
  workflow_call:

env:
  CMAKE_BUILD_TYPE: Release
  REST_PATH: /rest/legacylib/install
  LEGACY_LIB_PATH: legacylib
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:

  build-legacylib:
    name: Build only legacy
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/root-geant4-garfield:rest-for-physics
    steps:
      - uses: actions/checkout@v3
      - name: Build and install
        uses: rest-for-physics/framework/.github/actions/build@master
        with:
          cmake-flags: "-DCMAKE_INSTALL_PREFIX=${{ env.REST_PATH }} -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -DREST_WELCOME=ON -DRESTLIB_LEGACY=ON"
          branch: ${{ env.BRANCH_NAME }}
      - name: Load REST libraries
        run: |
          source ${{ env.REST_PATH }}/thisREST.sh
          restRoot -b -q
